# Generated by Django 5.0.7 on 2024-08-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rents", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rent",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="rent",
            name="is_paid",
        ),
        migrations.AddField(
            model_name="rent",
            name="rent_begin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rent",
            name="rent_stop",
            field=models.DateField(blank=True, null=True),
        ),
    ]
