# Generated by Django 5.0.7 on 2024-08-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="firstname",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="tenant",
            name="lastname",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
