# Generated by Django 5.0.7 on 2024-08-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_tenant_firstname_tenant_lastname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="lastname",
        ),
        migrations.AlterField(
            model_name="tenant",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
    ]
