# Generated by Django 5.0.7 on 2024-08-06 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_remove_tenant_firstname_remove_tenant_lastname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="flat",
        ),
    ]
