# Generated by Django 5.0.7 on 2024-08-06 01:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0005_tenant_flat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="username",
        ),
    ]
