# Generated by Django 5.0.7 on 2024-07-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=100)),
                ("street_name", models.CharField(max_length=255)),
                ("street_number", models.CharField(max_length=10)),
                ("flat_number", models.CharField(max_length=10)),
                ("flat_floor", models.IntegerField()),
                ("flat_size_sqm", models.FloatField()),
            ],
        ),
    ]
