# Generated by Django 5.0.7 on 2024-08-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cost",
            name="cost_is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
